server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/learning_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

  # 文件上传配置
  servlet:
    multipart:
      enabled: true                 # 启用文件上传
      max-file-size: 10MB          # 单个文件最大大小
      max-request-size: 50MB       # 单次请求最大大小
      file-size-threshold: 0       # 文件写入磁盘的阈值



mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.boda.springboot.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  level:
    com:
      boda:
        mapper: debug
        service: info
        controller: info

# JWT 配置
jwt:
  secret: d025897c-c962-49f2-9d98-0dfcc6485b97-web-lab-learning-system-secret-key # 密钥(至少32字节)
  expiration: 86400000  # 24小时(毫秒)
  header: Authorization # 请求头名称
  prefix: Bearer        # Token前缀

# Knife4j 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.boda.springboot.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表

# 七牛云配置
qiniu:
  access-key: 99penKAHZrNem2u0Kj4IeBWtX_pa_oMfwYBs-TAs    # 替换为您的 AccessKey
  secret-key: nGDvpf785zK6rSp40rP35Q7lV8jB9Oj5QALZ8FBt     # 替换为您的 SecretKey
  bucket: web-lab            # 替换为您的存储空间名称
  domain: t6caqcc3d.hd-bkt.clouddn.com        # 替换为您的 CDN 加速域名（带 http:// 或 https://）
  zone: z0                              # 存储区域: z0-华东, z1-华北, z2-华南, na0-北美, as0-东南亚
