spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/web_lab?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.boda.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  level:
    com:
      boda:
        mapper: debug
        service: info
        controller: info